### ISSUE TITLE
Solid Technology - React Framework

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viade_en3b#12]
We must learn the basics of the Solid Technology in order to start developing the application. 

Also, React framework must be studied, also for the development.

**Comment by PabloCanalSuarez** [comment]
Each member of the group should learn how the POD system of Solid works.

**Comment by PabloCanalSuarez** [comment]
Interesting resources:
https://solid.inrupt.com/how-it-works

https://solid.inrupt.com/docs/writing-solid-apps-with-react

https://solid.inrupt.com/get-a-solid-pod

https://solid.inrupt.com/docs/installing-running-nss

**Comment by CarmenVigo** [comment]
Those are such interesting and helpful resources, thanks for sharing :)
I did a little research about React and I think you'll find these links interesting as well...
https://reactjs.org/
https://facebook.github.io/react-native/

**Comment by CarmenVigo** [comment]
Hi, I consider it will be interesting if we assist this Wednesday's conference about Solid. It is here at the school at 11:30.
https://www.campusvirtual.uniovi.es/mod/forum/discuss.php?d=82385
