### ISSUE TITLE
Testing resources

### ISSUE THREAD

**Issue by MiguelCuestaM** [Arquisoft/viade_en3b#14]
I find that testing on different technologies could soon become difficult to do. Keeping track of what is already ok and what is not is bound to become a problem. I've found an interesting tool, check it to see if adding it to our project would be a good idea:

https://coveralls.io/features

If you like it, I will update the documentation on Solution Strategy to include this as our method of testing; and if not, we will live it as TBD for this version

**Comment by MiguelCuestaM** [comment]
I don't really know if this label was a good choice, or even if this should have been a part of the React-Node technology issue, making it more of a general "Needed technology" issue. Nevertheless, here you have it

**Comment by PabloCanalSuarez** [comment]
I think for the continuous integration testing we must use Travis, as well as Codecov and Codacy, which are tools that are already implemented in our repository. 

You can add the use of those technologies and services to the Solution Strategy of the documentation :)

**Comment by CarmenVigo** [comment]
Hi, I do not think codecov nor codacy will be great for our projects.
Check this link for better understanding:
https://www.slant.co/versus/7929/26428/~codecov_vs_codacy
It is marked as a comparison of both, but what it actually tells the pros and cons of both.
I'll check for alternatives when I get home, though based on my quick research I like code climate better than codacy :)
https://www.slant.co/versus/7927/7929/~code-climate_vs_codecov

**Comment by CarmenVigo** [comment]
Hi again, I believe JEST testing framework will be a great incorporation to our project.
What do you think?
https://www.browserstack.com/guide/top-javascript-testing-frameworks
https://blog.usejournal.com/jest-vs-mocha-whats-the-difference-235df75ffdf3
https://spin.atomicobject.com/2017/05/02/react-testing-jest-vs-mocha/
