### ISSUE TITLE
Codacy not able to process branches

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viade_en3b#30]
When doing a pull request to a non-master branch, codacy is not able to make the corresponding tests to pass the request. 

This is the same issue that the viade_en3a team had, and it requests a change in codacy by @labra 

Thank you.

**Comment by PabloCanalSuarez** [comment]
@pglez82 it would be great if you could help us with this issue, because taking into account what Labra told us the other day in class, we can't solve it as we are not the admins of the repository.

**Comment by pglez82** [comment]
I can enable this in codacy by manually choosing the branches to which Codacy has access. Currently you have the master and development branches getting analysed. Do you need me to enable any other?

**Comment by PabloCanalSuarez** [comment]
Oh, I forgot to indicate here that I managed to activate the development branch a couple of days ago. The only thing I had to do was to register in the Codacy web and then I was able to enable it. 

Thank you anyway, I will close this issue now.
