### ISSUE TITLE
Importing Routes

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viade_en3b#43]
Basic routes to use as possible examples are described here.

**Comment by CarmenVigo** [comment]
I think I need help.
My initial idea is to create a Route class, containing all its information, that could be both represented in the map and stored on the user's pod.
It seemed simple, but I am finding it pretty hard :)
I'll focus on the first part first.

**Comment by CarmenVigo** [comment]
I found the following (hopefully) interesting libraries:
https://github.com/awwright/node-rdf
https://github.com/Leaflet/Leaflet (more for the map visualization I believe)

**Comment by CarmenVigo** [comment]
I believe it will be better to rename this issue now :)

**Comment by CarmenVigo** [comment]
I'll be working on importing to viade routes in JSON-LD/Turtle formats.

**Comment by CarmenVigo** [comment]
So what it is left to do is:
-Read routes from pods
-Load the routes on the map (unable because of high coupling with demo route and the map)
Two issues will be created (one per topic) to be solved asap.
