### ISSUE TITLE
Home (Welcome) Window

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viade_en3b#55]
The application must have a home/welcome window. Very simple.

**Comment by ElenaRodriguezRio** [comment]
I think it should have just the login to access the application

**Comment by PabloCanalSuarez** [comment]
The login system is implemented in the NavBar. In case the user is not logged in, we must show some view, and that is the purpose of this Welcome Window.

It will have just a simply panel with some phrase like "Welcome to Viade", and the NavBar, where the buttons to register/login will be placed.

**Comment by ElenaRodriguezRio** [comment]
lgtm :)

**Comment by PabloCanalSuarez** [comment]
Final indexing looks like this:
```
<HashRouter>
    <Fragment>
      <Switch>
        <Route exact path="/404" component={PageNotFound} />
        <Redirect exact from="/" to="/welcome" />
        <Route exact path="/welcome" component={Welcome} />
        <Route exact path="/dashboard" component={Main} />
        <Route exact path="/register" component={Register}/>
        <Redirect to="/404" />
      </Switch>
    </Fragment>
  </HashRouter>
```
