### ISSUE TITLE
Documentation 04: Solution Strategy

### ISSUE THREAD

**Issue by CarmenVigo** [Arquisoft/viade_en3b#8]

**Comment by CarmenVigo** [comment]
Hi, more or less the Technology Decisions part is done. Check it out when you have time, I'll continue working on it tomorrow.

**Comment by CarmenVigo** [comment]
Sorry, I forgot to push branch "feature_arc42_04SolutionStrategy". Now my changes can be found on that branch!

**Comment by CarmenVigo** [comment]
I have filled as well the Organizational Decisions section, though feel free to add something that you considered I missed.

**Comment by MiguelCuestaM** [comment]
I finished Architectural Decisions and Quality Goals, and sent a request to merge both our develop branches. Check the conflicts to see my changes on your file, and then make a pull request to Master
